//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolderBrowser.Local {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FolderBrowser.Local.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path into Windows Clipboard....
        /// </summary>
        public static string CMD_Copy_Path_To_Clipboard_Label {
            get {
                return ResourceManager.GetString("CMD_Copy_Path_To_Clipboard_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as path into Windows clipboard..
        /// </summary>
        public static string CMD_Copy_Path_To_Clipboard_Label_TT {
            get {
                return ResourceManager.GetString("CMD_Copy_Path_To_Clipboard_Label_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open folder in Windows Explorer....
        /// </summary>
        public static string CMD_Open_in_Windows_Label {
            get {
                return ResourceManager.GetString("CMD_Open_in_Windows_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the Windows Explorer with the selected folder..
        /// </summary>
        public static string CMD_Open_in_Windows_Label_TT {
            get {
                return ResourceManager.GetString("CMD_Open_in_Windows_Label_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark folder.
        /// </summary>
        public static string CMD_RecentFolderAdd_Label {
            get {
                return ResourceManager.GetString("CMD_RecentFolderAdd_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds the selected folder to the list of bookmarked folders..
        /// </summary>
        public static string CMD_RecentFolderAdd_TT {
            get {
                return ResourceManager.GetString("CMD_RecentFolderAdd_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete folder bookmark.
        /// </summary>
        public static string CMD_RecentFolderRemove_Label {
            get {
                return ResourceManager.GetString("CMD_RecentFolderRemove_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the selected folder from the list of recent folders..
        /// </summary>
        public static string CMD_RecentFolderRemove_TT {
            get {
                return ResourceManager.GetString("CMD_RecentFolderRemove_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder....
        /// </summary>
        public static string CMD_Select_Folder_Label {
            get {
                return ResourceManager.GetString("CMD_Select_Folder_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the current folder and updates all related views..
        /// </summary>
        public static string CMD_Select_Folder_Label_TT {
            get {
                return ResourceManager.GetString("CMD_Select_Folder_Label_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is not ready..
        /// </summary>
        public static string STR_MSG_DEVICE_NOT_READY {
            get {
                return ResourceManager.GetString("STR_MSG_DEVICE_NOT_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &apos;{0}&apos; does not exist or cannot be accessed..
        /// </summary>
        public static string STR_MSG_DIRECTORY_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("STR_MSG_DIRECTORY_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error finding requested resource..
        /// </summary>
        public static string STR_MSG_ERROR_FINDING_RESOURCE {
            get {
                return ResourceManager.GetString("STR_MSG_ERROR_FINDING_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured..
        /// </summary>
        public static string STR_MSG_UnknownError {
            get {
                return ResourceManager.GetString("STR_MSG_UnknownError", resourceCulture);
            }
        }
    }
}
